### ISSUE TITLE
Milestone 3 - R Checklist

### ISSUE THREAD

**Issue by lynnwbl** [UBC-MDS/textfeatureinfor#10]
- [x] R functions unit tests (and their documentations)
- [x] R functions internal code
    - Exception handling
- [x] Test if our R package can be installed from Github and used
