### ISSUE TITLE
Milestone 4 tasks

### ISSUE THREAD

**Issue by paradise1260** [UBC-MDS/textfeatureinfor#34]
- [x] Github actions for R CMD check and tests - Jacqueline
- [x] upload results to codecov - Kiran
- [x] vignette (full demo of package via examples, installation instruction in readme, review Roxygen2 documentation) - everyone
- [x] pkgdown (full demo of package via examples, installation instruction in readme, review Roxygen2 documentation) - Paniz
- [x] examine the license and change it if needs be. (If changed, update python license as well) - Discussion through Github issue, we need to submit the link to the issues. - everyone
- [x] initiate package review request- done by Jacqueline
